### ISSUE TITLE
Publish static libraries for NativeAOT

### ISSUE THREAD

**Issue by Ristovski** [danilwhale/Raylib-cs.BleedingEdge#3]
NativeAOT does not support `IncludeNativeLibrariesForSelfExtract` (https://github.com/dotnet/sdk/issues/39202), it would be nice if this project included a static library along with the shared one, so it could be statically linked into the final executable, allowing to publish single-file apps.

As it stands right now, this copies the `libraylib.so` next to the self-contained/NativeAOT binary.

Edit: Changing `-D BUILD_SHARED_LIBS=ON` to `-D BUILD_SHARED_LIBS=OFF` seems to Just Work(tm), so perhaps a build-time parameter can be implemented for `dotnet build Raylib-cs.BleedingEdge.Native` so that it can be invoked twice when building the resulting published package, once with the static lib and once with the shared one?

**Comment by danilwhale** [comment]
What about making 2 .Runtimes packages (.Shared and .Static) and 2 packages that reference .Shared or .Static and main package? I'm not really sure about this decision, but it's probably only a good one.

**Comment by danilwhale** [comment]
Actually, I'll just make .CustomNative package, because it will be more useful.

**Comment by danilwhale** [comment]
Sorry, but MSBuild is terrible to work with, you can now read README how to customize raylib build
Also, static libraries are now published in [workflow](https://github.com/danilwhale/Raylib-cs.BleedingEdge/actions/workflows/build-static-natives.yaml)

**Comment by Ristovski** [comment]
Good enough for me, thanks!
