### ISSUE TITLE
DrawSphereWires() is missing.

### ISSUE THREAD

**Issue by alecpizz** [danilwhale/Raylib-cs.BleedingEdge#4]
DrawSphereWires is missing from the wrapped methods, DrawSphereEx and DrawSphere are present though!

**Comment by danilwhale** [comment]
my bad :)
i'm busy with rebranding the binding and adding examples though, you can add DrawSphereWires to your code for now:
```cs
[UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
[LibraryImport("raylib")]
public static partial void DrawSphereWires(Vector3 centerPos, float radius, int rings, int slices, Color color);
```

**Comment by alecpizz** [comment]
Awesome, thank you!
